### ISSUE TITLE
deque use cases? 

### ISSUE THREAD

**Issue by manzoid** [phf/go-queue#1]
Hi @phf 

This is a nice and nicely-annotated implementation.

In your uni class, how do you explain the practical utility of dequeues?  I have searched for a while and found many mentions of just this single, specialized use case pertaining to multi-processor job scheduling: https://en.wikipedia.org/wiki/Double-ended_queue#Applications   That's a bit arcane.

I think it's also usable for a ring buffer, which has student-intuitive uses for data buffering.

Elsewhere I saw mention of using dequeues for undo/redo cases, although normal stacks seem ok for that...?  Unless something needs to be done with the bottom of the stack... maybe because it's fixed size and the bottom needs to be evicted(?)  

So, struggling a bit to come up with a tidy set of student-convincing stuff.

Thanks--

**Comment by phf** [comment]
Sorry, didn't see this for a while. I am not sure why there's a need for "more" use cases, the usual ones seem plenty? I've been using a lot of queues last year as part of a distributed messaging infrastructure. Do you need deques for that? Not really. It *can* be useful if you want to "stick a message back" for whatever reason, but to me the main argument always came down to "it's not much harder to do and it doesn't cost performance, so why wouldn't you make a deque instead of a queue?" </shrug>

**Comment by manzoid** [comment]
Hi @phf --

Yes, the why not? argument is reasonable.  It makes sense to use a deque for the free flexibility.  

Thanks :D
